# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be7c7b51d5de4ac3dffed9eb3812264b178d9044cedaae01a82b1f90c12eb9d5e70a720623ad2086d2d4b8c884e284c4a9aa34c1b724b2948155c68e84256aec

test:
  secret_key_base: d23f95e357afd7615805b303edd9212183158be71f2e3610f5ff2d64d854e59b43cca51cddcdfa91ac9f86c3f6bbb7ebc5ed2e22881b4bb513d66aa5d4d417f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
