number_percent_training: 0.7
per_page:
  admin:
    data_cancer: 10
    knowledge: 10
    user: 10
    diagnose: 4
    group: 6
    rules: 10
    fictions: 5
    value_fictions: 10
image_format_accept: "image/jpeg,image/gif,image/png"
image_default: "group_default.gif"
user:
  name_max: 5
  code_admin: "A"
  code_patient: "P"
  code_owner: "D"

fiction:
  clump_thickness: "Clump Thickness"
  uniformity_of_cell_size: "Uniformity of Cell Size"
  uniformity_of_cell_shape: "Uniformity of Cell Shape"
  marginal_adhesion: "Marginal Adhesion"
  single_epithelial_cell_size: "Single Epithelial Cell Size"
  bare_nuclei: "Bare Nuclei"
  bland_chromatin: "Bland Chromatin"
  normal_nucleoli: "Normal Nucleoli"
  mitoses: "Mitoses"

image_types:
  jpg: "jpg"
  jpeg: "jpeg"
  gif: "gif"
  png: "png"


bg1: "bg1.jpg"
bg2: "bg2.jpg"
bg3: "bg3.jpg"
bg4: "bg4.jpg"
bg5: "bg5.jpg"
bg6: "bg6.jpg"
