per_page:
  admin:
    data_cancer: 10
    knowledge: 10
    user: 10
image_format_accept: "image/jpeg,image/gif,image/png"
image_default: "group_default.gif"
user:
  name_max: 5

fiction:
  clump_thickness: "Clump Thickness"
  uniformity_of_cell_size: "Uniformity of Cell Size"
  uniformity_of_cell_shape: "Uniformity of Cell Shape"
  marginal_adhesion: "Marginal Adhesion"
  single_epithelial_cell_size: "Single Epithelial Cell Size"
  bare_nuclei: "Bare Nuclei"
  bland_chromatin: "Bland Chromatin"
  normal_nucleoli: "Normal Nucleoli"
  mitoses: "Mitoses"
